### PR TITLE
Add better-cond clj-kondo config by @genovese

### PR DESCRIPTION
**Pull request by borkdude**
@Engelberg This adds a clj-kondo config per discussion in https://github.com/clj-kondo/config/pull/15.

Additionally it fixes all lint warnings in this project:

```
$ clj-kondo --lint src:test
linting took 150ms, errors: 0, warnings: 0
```

Additionally it moves tests to .cljc so they can run with CLJS:

```
$ clj -Sdeps '{:paths ["src" "test"] :deps {org.clojure/clojurescript {:git/url "https://github.com/clojure/clojurescript" :git/sha "02b450af9c5f3a1fa2ee949c28c3a671987d7e54"}}}' -M -m cljs.main -re node
ClojureScript 0.0.1828047738
cljs.user=> (require '[clojure.test :as test])
nil
cljs.user=> (require '[better-cond.core-test])
nil
cljs.user=> (test/run-tests 'better-cond.core-test)

Testing better-cond.core-test

Ran 1 tests containing 11 assertions.
0 failures, 0 errors.
nil
cljs.user=>
```

### CODE REVIEW

**Comment by borkdude** [comment]
@Engelberg This adds a clj-kondo config per discussion in https://github.com/clj-kondo/config/pull/15.

Additionally it fixes all lint warnings in this project:

```
$ clj-kondo --lint src:test
linting took 150ms, errors: 0, warnings: 0
```

Additionally it moves tests to .cljc so they can run with CLJS:

```
$ clj -Sdeps '{:paths ["src" "test"] :deps {org.clojure/clojurescript {:git/url "https://github.com/clojure/clojurescript" :git/sha "02b450af9c5f3a1fa2ee949c28c3a671987d7e54"}}}' -M -m cljs.main -re node
ClojureScript 0.0.1828047738
cljs.user=> (require '[clojure.test :as test])
nil
cljs.user=> (require '[better-cond.core-test])
nil
cljs.user=> (test/run-tests 'better-cond.core-test)

Testing better-cond.core-test

Ran 1 tests containing 11 assertions.
0 failures, 0 errors.
nil
cljs.user=>
```

**Comment by Engelberg** [comment]
Thanks for providing the pull request!

**Comment by Engelberg** [comment]
Question for @borkdude : I just received an issue that the clj-kondo config is having a negative impact on cursive. https://github.com/Engelberg/better-cond/issues/5#issuecomment-998033203 Have you seen this and do you know what is causing it? Thanks.

**Comment by borkdude** [comment]
I replied in the issue.

**Comment by Engelberg** [comment]
Just for fun, I tried out Calva, and it seems that its built-in clj-kondo is drawing squiggly red lines under everything defined with and in the defnc macro from better-cond, even using this latest version of better-cond that has the clj-kondo config. Any ideas?

**Comment by borkdude** [comment]
@Engelberg After clojure-lsp (which comes with Calva) indexes your project, you should have the config in `.clj-kondo/better-cond/better-cond` in your project. But you might have to create `.clj-kondo` in your project first before clojure-lsp writes there. So try doing that and restart Calva, and wait a while.

**Comment by borkdude** [comment]
I'm going to try this locally and will let you know. /cc @ericdallo

**Comment by ericdallo** [comment]
Clojure-lsp already creates the .clj-kondo dir to avoid issues like that,.maybe the issue is another thing?

**Comment by borkdude** [comment]
@Engelberg A few things to note:

1) You have to open VSCode in the root dir of the project. This is important in most projects you work in in VSCode.
2) clojure-lsp automatically picks up on your deps.edn but this might take a while. After that is done, you should see a `.clj-kondo/better-cond` folder in your project. You might have to edit a file and/or restart VSCode, not sure.
3) When editing files, you should see correct linting. 

Screen Shot 2022-01-14 at 13 21 48

**Comment by borkdude** [comment]
A darn, I overlooked that you are talking about `defnc` specifically. There is no hook support for that yet, but we could make that work.

**Comment by borkdude** [comment]
@Engelberg This config seems to do the trick:

Adding to `better-cond.core` in the config:

``` clojure
(def defnc-hook
  (fn [{:keys [node]}]
    (let [[name-node arg-node & body]
          (rest (:children node))
          new-node (api/list-node [(api/token-node 'clojure.core/defn) 
                                   name-node
                                   arg-node
                                   (api/list-node
                                    (list* (api/token-node 'better-cond.core/cond)
                                           body))])]
      {:node new-node})))
```

The `config.edn`:

``` clojure
{:hooks
 {:analyze-call {better-cond.core/cond better-cond.core/cond-hook
                 better-cond.core/defnc better-cond.core/defnc-hook}}
 :lint-as
 {better-cond.core/if-let clojure.core/let
  better-cond.core/when-let clojure.core/let}}
```

**Comment by borkdude** [comment]
@Engelberg Do you want me to add this is a PR to improve the config for `defnc`?

**Comment by Engelberg** [comment]
That would be great. Also `defnc-`.

Does the existing config handle the things from better-cond that shadow stuff in core, like: when-let if-let when-some if-some
?

**Comment by borkdude** [comment]
@Engelberg Perhaps you can prepare a branch with some tests or examples that should be linted correctly? Then I can make a PR based on those examples which fixes the linting, if it wasn't already covered.

**Comment by Engelberg** [comment]
OK, I won't have a chance to do that until Tuesday at the earliest, but I will do it then.

**Comment by borkdude** [comment]
OK, just ping me when you have something.

**Comment by Engelberg** [comment]
@borkdude More test cases added to lint branch

**Comment by borkdude** [comment]
@Engelberg Thanks. I hope to take a look later this week.

**Comment by borkdude** [comment]
@Engelberg https://github.com/Engelberg/better-cond/pull/22

I also included a CI setup using Github Actions for testing on the JVM, on CLJS and using clj-kondo.

**Pull request merged**
