### PR TITLE
V2.0.1

### PR DESCRIPTION
**Pull request by madstap**
This fixes some problems I was having with clojurescript.

### CODE REVIEW

**Comment by Engelberg** [comment]
I appreciate the contribution.  Can you explain a little more about what problems this pull request solves?  Because offhand, I don't see why any of these changes would make a difference.  Thanks.

**Comment by madstap** [comment]
I wrote this PR to start a discussion on the best way to proceed. After bumbling about a bit with some  trial and error, this makes my cljs build error and warning free when I have a project depending on better-cond. (using browser cljs v.1.9.562)

There seems to be three problems.

## Macro inference

This is not actually a "problem", more of a nice to have...

Apparently, when there's both a clj namespace with macros, and a cljs namespace with the same name, if the cljs namespace does `:require-macros` to it's own namespace, a cljs consumer can require it normally.

[mfikes explains it better](http://blog.fikesfarm.com/posts/2016-03-01-clojurescript-macro-sugar.html#implicit_sugar)

I tried it with just `#(:cljs (:require-macros [better-cond.core]))`, but I got warnings about missing vars (although the library still works ¯\\\_(ツ)_/¯). When do `#?(:cljs (:require-macros [better-cond.core :refer [cond when-let if-let]]))` everything works, and as a cljs consumer I can require normally without doing `:require-macros`.

## clojure.core/defnc spec

There's a `fdef` for `defnc`, which makes sense. There's also a `fdef` for `clojure.core/defnc`, which doesn't make sense? I gives this warning in cljs, so I removed it.

    ----  Could not Analyze  /home/madstap/code/better-cond/src/better_cond/core.cljc   line:157  column:1  ----

    Assert failed: Unable to resolve: clojure.core/defnc
    v

    155             :ret any?)
    156  
    157  (spec/fdef clojure.core/defnc
           ^--- Assert failed: Unable to resolve: clojure.core/defnc
           v
    158    :args ::defn-args
    159    :ret any?)

    ----  Analysis Error : Please see /home/madstap/code/better-cond/src/better_cond/core.cljc  ----

## Copy paste code from clojure.core.specs

The `clojure.core.specs.alpha` namespace doesn't seem to be ported to cljs yet. Cljs refuses to build, with the following error.

    Caused by: clojure.lang.ExceptionInfo: No such namespace: clojure.core.specs.alpha, could not locate clojure/core/specs/alpha.cljs, clojure/core/specs/alpha.cljc, or Closure namespace "clojure.core.specs.alpha" in file /home/madstap/code/better-cond/src/better_cond/core.cljc {:tag :cljs/analysis-error}

We could wrap every spec in `#(:clj ,,,)`, but since there was already some specs taken from there, I thought it'd be easier just to copy the relevant parts for now. I figure they're gonna be ported at some point , and this commit can be reverted when that happens.

## There's no tests

I think this project could really use some simple tests running in clj, browser cljs and self hosted cljs. Maybe that should be in place before this PR is accepted? I don't know anything about self hosted, but I did set up some clj/cljs tests the other day by seeing how [medley](https://github.com/weavejester/medley) does it. Would you accept a PR with a similar setup?

**Comment by Engelberg** [comment]
I believe that Fikes blog post is out of date, and currently, require is automatically supported with no need for a self-referencing require-macros.  I don't recall having any difficulty using require as opposed to require-macros; I will double-check.

I also don't recall seeing any errors from the clojure.core.specs.alpha and I would expect feature parity on this between Clojure and Clojurescript based on the announcement (https://groups.google.com/forum/#!msg/clojure/10dbF7w2IQo/ec37TzP5AQAJ).  But if the use of clojure.core.specs.alpha is causing problems, then I agree with your solution.

Yeah, I can't think of any reason why the clojure.core/defnc spec should be there.  Probably an oversight on my part.

You're right that I haven't included a test suite, and that seems worthwhile to pursue.  aengelberg did a great job setting up github.com/Engelberg/instaparse with a test framework that supported cljs.  If possible, I'd like to use that as a model, because it's what I'm now familiar with and I know I can run the tests on my system.  Could you take a look at that and see how easy it would be to adopt that for use with better-cond?

Thanks.

**Comment by Engelberg** [comment]
I've confirmed that everything works fine if you use `:require-macros` rather than `:require`.   With require, as you point out, things break down because of clojure.core.specs.alpha.  I'm still not sure the self-requiring trick is needed in the latest versions of clojurescript -- I haven't tested that yet.

**Comment by Engelberg** [comment]
I'm thinking it would be advisable to use :require-macros all the time anyway, otherwise by loading this in Clojurescript you're creating all these specs in the global registry as part of your clojurescript application, which is totally unnecessary overhead.

**Comment by Engelberg** [comment]
OK, so here's what I've done so far.

I've updated the README to explain the need for using :require-macros.  (I had such a notice in the 1.0.1 branch, but had removed it from 2.0.1 because I had thought that renaming the file to .cljc would be enough to make it work with :require).

I fixed that extraneous fdef (it was supposed to be an fdef for `defnc-`).

So the only question in my mind is whether to port all those specs as per your pull request so it can work with :require.  The downside is that it will create these specs in the spec registry as part of the clojurescript runtime, whereas with :require-macros the specs are only needed at compile-time by the Clojure-based compiler.  So my inclination is to continue to recommend the use of :require-macros.  What do you think?

**Comment by madstap** [comment]
I didn't think to try using not-porting-the-core-specs and :require-macros together. Apparently I'm still missing something in my understanding of cljs macros.

So then  the tradeoff is between extra specs in the registry, which presumably means slightly bigger js code size (memory consumption?) and the convenience of consistent requiring (less conditionals in cljc).

This tradeoff will stay the same as `specs.alpha` is ported to cljs, and the specs are removed from this repo.

In the self-hosted case, does that mean that the defnc form won't be checked by spec at macroexpansion time?

Personally I think the convenience is worth it, especially for writing portable code. Will it be _that_ expensive?

**Comment by Engelberg** [comment]
I checked with Mike Fikes, and he says the trick of self require-macros is still necessary for require to work from other files, as you said.

So, no changes are needed if we only want to support require-macros, or both changes you recommended if we want to support require.

Using require will result in a slightly bigger js/memory footprint.

I'm not opposed to making it *possible* to use require, but I think I'll still recommend using require-macros in clojurescript.

I would imagine that self-hosted, everything happens whenever the clojurescript compiler compiles the code, but I'm not too familiar with the quirks of self-hosting.

**Comment by Engelberg** [comment]
I think you may have misunderstood one of my points.  It's not just the extra specs ported from clojure.core.specs.alpha that would be an issue, it's all the specs.  With :require-macros, the clojurescript code never executes anything in the cljc file (on the Clojure compiler does), so none of these specs get loaded.

**Comment by Engelberg** [comment]
I split it into two files so there will be no performance penalty above and beyond previous version for Clojure users or Clojurescript users using :require-macros.  As you pointed out, there's no test suite currently; I think this should work, but let me know if you encounter any further difficulties.

**Comment by madstap** [comment]
If the consumer can choose whether they want to pay the perf penalty, that's great, better-cond doesn't need to make the tradeoff for them. With your newest change, my project now works with no warnings or errors, and I can `:require` in cljs.

I will try to get a test suite going sometime during this week, using instaparse as an example.

**Pull request closed without merging**
