### PR TITLE
Fix refer usage of cond.

### PR DESCRIPTION
**Pull request by RyanMcG**

### CODE REVIEW

**Comment by Engelberg** [comment]
Thanks.  Glad you found the repository.  Do you have any questions?  I haven't done much with the README yet.

**Comment by Engelberg** [comment]
It also supports :when-let with a binding vector of one or more names (only passes if all are not nil).

There's also a kind of support for if-let inside the cond, but I never really use that one.

**Comment by RyanMcG** [comment]
No questions at the moment. I follow you and I often take a peak at new repositories when the come up in my feed. I just happened to notice this super minor issue in the README.

**Comment by Engelberg** [comment]
OK, thanks.

**Pull request merged**
